BEGIN;
  TRUNCATE "User" RESTART IDENTITY CASCADE;
  TRUNCATE "ObraSocial" RESTART IDENTITY CASCADE;
  TRUNCATE "Profesional" RESTART IDENTITY CASCADE;
  TRUNCATE "ProfesionalObraSocial" RESTART IDENTITY CASCADE;
  TRUNCATE "Paciente" RESTART IDENTITY CASCADE;
  TRUNCATE "HistoriaClinica" RESTART IDENTITY CASCADE;
  TRUNCATE "Turno" RESTART IDENTITY CASCADE;
COMMIT;